### ISSUE TITLE
Sometimes no image is served

### ISSUE THREAD

**Issue by cmeeren** [ambroisemaupate/intervention-request#10]
I have a cross-browser issue where sometimes, no image is served. There is nothing in the log about this (only "GC started", "GC completed"), and it happens with new images as well as images served only a second ago. This is normally fixed by a page reload, but it can reappear on the next page load. I wish I could provide further details, but I have not been able to find anything reproducible - it seems to happen entirely at random.

Anyone else experiencing this?

**Comment by ambroisemaupate** [comment]
Could you paste here a link to your `phpinfo()` output to try to reproduce the issue with the same configuration.

**Comment by cmeeren** [comment]
It's a local server. Is there any way I can send you the phpinfo html file?

**Comment by ambroisemaupate** [comment]
You can send it to my email ambroise[at]rezo-zero.com

**Comment by ambroisemaupate** [comment]
Hi @cmeeren 
I don’t manage to reproduce your problem. Can you try with default WAMP setup with PHP 5.5 ?
I tried on our MAMP with php 5.6 and with a _OVH_ shared hosting with php 5.6 too, there is no problem on first request and repeated requests.

Can you activate `xdebug` extension and set `display_errors` php variable to `1`. It should display the error instead of a blank page when your issue occurs.

**Comment by cmeeren** [comment]
Hi, just want you to know I'll have to get back to this. I'm loaded with other tasks for the moment, and I can't seem to reliably reproduce these errors on the live server.

I have been considering whether this could be an effect of using [picturefill](https://github.com/scottjehl/picturefill), but I haven't tested that (a bit difficult since I can't reliably reproduce this error).

**Comment by ambroisemaupate** [comment]
Hi, do you see the _response code_ for these images in your Chrome Devtools > Console or in the Resources panel. I didn’t get your error since our last messages. Try without picturefill, but I doubt this comes from a _front_ script issue.

**Comment by cmeeren** [comment]
I am sorry, but now I can't even seem to reproduce the problem on my local testing server. Everything works fine. I will update with the response code and more info if the problem reappears.
