### ISSUE TITLE
Possible to remove cache of a single image?

### ISSUE THREAD

**Issue by cmeeren** [ambroisemaupate/intervention-request#12]
I have IR running wonderfully on my site. I have an image I have to replace with a corrected version, and the backend will make it tedious beyond reason to use a new filename. Is there some way I can remove specific images (i.e., all cached/resized versions of specific originals) in IR so that they will be re-built using the updated original?

**Comment by ambroisemaupate** [comment]
Did you try using `setUseFileChecksum(true)` in IR configuration so that it checks your file last modification date to see if it can serve from cache or not. It takes a little more time but it can be useful if you can’t change your file name.

**Comment by cmeeren** [comment]
Tried adding `$conf->setUseFileChecksum(true);`, but then all images disappeared. What could be the cause of that?

**Comment by ambroisemaupate** [comment]
You might have a PHP error, can you check your php log or activate `displayErrors` on your webserver and request directly an image to see if any error message pops out.

File checksum uses `adler32` hash algorithm. Can you test if it’s available on your webserver.

 `$fileMd5 = hash_file('adler32', $this->realImage->getPathname());`

**Comment by cmeeren** [comment]
The error log was full of `PHP Fatal error:  Call to undefined method AM\\InterventionRequest\\Configuration::setUseFileChecksum() in <snip>/intervention-request/index.php on line 60` where line 60 is where I added `$conf->setUseFileChecksum(true);`.

**Comment by ambroisemaupate** [comment]
Ahhh, did you update to latest InterventionRequest ? 

https://github.com/ambroisemaupate/intervention-request/releases/tag/v0.1.5

**Comment by cmeeren** [comment]
Works now. Thanks!
