### ISSUE TITLE
question about RAM and performance

### ISSUE THREAD

**Issue by designosis** [ambroisemaupate/intervention-request#15]
I'm seeing some odd performance metrics on basic JPEG resizing. What I'm finding is that with some images, I need to set memory unusually high, and processing takes much longer than I'd expect (based on basic experience with both GD/PHP image resizing and SLIR).

My config is as follows:

```
ini_set('memory_limit', '32M');
$conf->setCachePath(APP_ROOT . '/cache');
$conf->setImagesPath(APP_ROOT . '/raw');
// $conf->setJpegoptimPath('/usr/local/bin/jpegoptim');
// $conf->setPngquantPath('/usr/local/bin/pngquant');
$conf->setUseFileChecksum(false);
$conf->setDefaultQuality(80);
```

The request is simply this:

```
http://ir_test.dev/images/?image=1.jpg&width=300
```

And the filesize, minimum required memory_limit to succeed, and processing times are:

```
0.5 MB image ... memory_limit =   1M ... <1 second
0.8 MB image ... memory_limit =  80M ...  6 seconds
1.6 MB image ... memory_limit = 170M ... 10 seconds
2.7 MB image ... memory_limit =  44M ...  5 seconds
5.8 MB image ... memory_limit =  66M ...  7 seconds
```

If I set memory limit any lower than the above for a given image, it errors out.

Also I noticed what could be an algorithm flaw ... it's difficult to describe, but it seems like failed conversions are still cached in some way. Meaning, if I make a request that fails due to insufficient memory, up the memory to a good level, then reload, it still fails. But then incrementing the width by 1 works. Hope that was clear.

I'm running PHP 7.0.10 on the latest MAMP PRO (4.0.5), which admittedly is a bit buggy, so it's possible that this problem is unique to my setup. Strange thing is how consistent the above numbers are per image (incrementing the width by 1 each time I test it).

I haven't tested anything on a production server yet, but I thought I'd check in and see if this was unusual :)

Thanks!

**Comment by ambroisemaupate** [comment]
@neokio Hi, thanks for your feedback! Did you try to perform directly your tests with base lib [Image-intervention](https://github.com/Intervention/image) to find out if the issue is from _IR_ or _Image-Intervention_ or even _GD_?

**Comment by designosis** [comment]
Just did a simple GD-only resize, and sure enough the issue is with MAMP's new GD implementation. Apologies for not testing that out before asking!  Please delete this entire thread :)
