### ISSUE TITLE
Symfony major release version

### ISSUE THREAD

**Issue by designosis** [ambroisemaupate/intervention-request#16]
More a question than an issue. This dependency ...

```
% composer depends symfony/http-foundation
ambroisemaupate/intervention-request  v0.1.8  requires  symfony/http-foundation (~2.8)
```
... prevents composer from updating symfony from 2.8.17 to 3.2.3. Which is fine, both major releases 2 and 3 are still actively maintained (as recently as 4 days ago for both). But release 3 is a year and a half old. I don't know enough about it to have an opinion, but I'm curious why you've chosen to stick with 2.8 :)

**Comment by ambroisemaupate** [comment]
Hi @neokio thanks for your suggestion. I totally agree with you, intervention-request doesn’t need to stick with 2.8 unless you’re still using php 5.4.

I’ll try to update that soon, or I accept PR if you have time.

**Comment by designosis** [comment]
PR done (hopefully correctly).
