### ISSUE TITLE
symfony/console dependency

### ISSUE THREAD

**Issue by designosis** [ambroisemaupate/intervention-request#23]
Hi! More a question than an issue. This Intervention Request dependency ...

    `ambroisemaupate/intervention-request v4.0.1 requires symfony/console (^4.4 || ^5.0.7)`

Is interfering with a number of components I'd love to use, all of which require `symfony/console ^6` (released ~2 years ago).

Any chance you'd consider updating this?

Thanks :)

**Comment by ambroisemaupate** [comment]
Hello @designosis 

v4.0.2 should allow symfony 6.* components. Thanks for your feedback
