### ISSUE TITLE
Docs are missing some stuff :)

### ISSUE THREAD

**Issue by designosis** [ambroisemaupate/intervention-request#25]
Hi! I just updated to latest version, and it took me a while to get things working. It appears the code in the section titled **`Using as a library inside your projects`** is missing some things. Specifically ...

### 1)
Without these two lines after `use AM\InterventionRequest\LocalFileResolver;` ...
```
use Symfony\Component\HttpFoundation\Request;
$request = Request::createFromGlobals();
```
... it won't work, as `$request` is used repeatedly in the rest of the codebase. If there's a way for it to work without Symfony, I'd be happy see it!

### 2)
The closing call ...
```
return $intRequest->getResponse($request);
```
... doesn't output to screen. It only works when I close with ...
```
$intRequest->getResponse($request)->send();
```  
  
  
###
In all, the minimum to get things working was:
```
use AM\InterventionRequest\Configuration;
use AM\InterventionRequest\InterventionRequest;
use AM\InterventionRequest\LocalFileResolver;

use Symfony\Component\HttpFoundation\Request;
$request = Request::createFromGlobals();

$conf = new Configuration();
$conf->setCachePath(APP_ROOT .'/cache');
$conf->setImagesPath(APP_ROOT);

$fileResolver = new LocalFileResolver($conf->getImagesPath());

$intRequest = new InterventionRequest($conf, $fileResolver);
$intRequest->handleRequest($request);
$intRequest->getResponse($request)->send();
```

... and with `ShortUrlExpander` and other bits I use ...

```
use AM\InterventionRequest\Configuration;
use AM\InterventionRequest\InterventionRequest;
use AM\InterventionRequest\LocalFileResolver;

use Symfony\Component\HttpFoundation\Request;
$request = Request::createFromGlobals();

$conf = new Configuration();
$conf->setCachePath(APP_ROOT .'/cache');
$conf->setImagesPath(APP_ROOT);
$conf->setDefaultQuality( 95 );
$conf->setJpegoptimPath('/usr/local/bin/jpegoptim'); // JPEG post-processing
$conf->setPngquantPath('/usr/local/bin/pngquant'); // PNG post-processing

// ShortUrlExpander
use AM\InterventionRequest\ShortUrlExpander;
$expander = new ShortUrlExpander($request);
$params = $expander->parsePathInfo();
if (null !== $params) {
    $expander->injectParamsToRequest($params['queryString'], $params['filename']);
}

$fileResolver = new LocalFileResolver($conf->getImagesPath());

$intRequest = new InterventionRequest($conf, $fileResolver);
$intRequest->handleRequest($request);
$intRequest->getResponse($request)->send();
```

**Comment by ambroisemaupate** [comment]
Hi @designosis 

This is library is designed to work with Symfony components.

https://github.com/ambroisemaupate/intervention-request?tab=readme-ov-file#using-as-a-library-inside-your-projects

Documentation in this section is meant to be used inside a project that use *Request / Response* behaviour. So I assume that you provide your `Request` object and you expect a `Response` object, not to send it right away.

```
// getResponse returns a Symfony\Component\HttpFoundation\Response object
// with image mime-type and data. All you need is to send it!
return $intRequest->getResponse($request);
```

What you describe is more like a standalone behaviour, just look at the `web/index.php` file : 

https://github.com/ambroisemaupate/intervention-request/blob/master/web/index.php

This is a standalone entrypoint to use this library as a server (or via Docker). You'll find all the points you listed in your issue on lines 25 and 90. This file will show you how to initialize all optional tools like ShortUrlExpander, or AWS filesystem adapter.

If you think documentation should be more detailled on these, feel free to create a Pull request.

**Comment by designosis** [comment]
Thank you, makes sense :)
