### ISSUE TITLE
How to install manually?

### ISSUE THREAD

**Issue by cmeeren** [ambroisemaupate/intervention-request#5]
The readme only specifies how to install this with composer. How do I install it manually?

**Comment by ambroisemaupate** [comment]
Hi @cmeeren,

_Composer_ is necessary to download this library dependencies. All you need is to clone this repository to your webserver, or your computer, then install _Composer_ and type `composer install --no-dev -o`.

See https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx

I invite you to take a look to _Composer_ if you are new to PHP, it’s the standard dependency management tool. It’s the same as _Rails_ for _Ruby_ and _NPM_ for _javascript_.

**Comment by ambroisemaupate** [comment]
@cmeeren  If you want, I can create a _Github Release_ with a ZIP file containing composer dependencies already downloaded. You would just have to unzip and configure `index.php` to match your website settings.

**Comment by ambroisemaupate** [comment]
@cmeeren Go to https://github.com/ambroisemaupate/intervention-request/releases/tag/v0.1.4

Then you can download the `intervention-request-0-1-4.zip` file. All is bundled inside.

**Comment by cmeeren** [comment]
Thanks!

**Comment by ambroisemaupate** [comment]
@cmeeren you’re welcome, do not hesitate to give your feedback.
