### ISSUE TITLE
Is it possible to set defaults when using as stand-alone application?

### ISSUE THREAD

**Issue by cmeeren** [ambroisemaupate/intervention-request#6]
I'm using it as a stand-alone application via index.php. Can I easily set some defaults and not have to include them in all img sources? For example, I would like the default quality to be 95, not 90.

**Comment by ambroisemaupate** [comment]
Try to inject manually quality to your `$request` object.

``` php
# In your index.php after $request = Request::createFromGlobals();
if (!$request->query->has('quality')) {
    $request->query->set('quality', 95);
}
```

I will set this parameter customizable via `Configuration` object later.

**Comment by cmeeren** [comment]
I am using intervention-request in a pure HTML sense, as in `<img src="/intervention-request/w500/path/to/image.jpg">`. What you say does not really make sense to me. Is there maybe a file where I can set some defaults, like SLIR?

**Comment by ambroisemaupate** [comment]
My example is to apply in your `/intervention-request/index.php` file which is your intervention-request entry-point. This is the file where you can set some defaults. Do not forget to create a `.htaccess` file in your `/intervention-request` folder according to the README.

**Comment by cmeeren** [comment]
Thank you, it seems to work. :smiley:

**Comment by ambroisemaupate** [comment]
Cool !
