### ISSUE TITLE
Cached image served when original image has changed

### ISSUE THREAD

**Issue by Toutouwai** [ambroisemaupate/intervention-request#7]
Currently Intervention-request serves a cached image when the original source image has changed.

Suppose I use Intervention-request to display the image "animal.jpg", which is a photo of a cat.
I then overwrite "animal.jpg" with a completely different photo of a dog.
Intervention-request does not detect that "animal.jpg" has changed and continues to serve the cached photo of the cat.

Maybe some aspects of the source image (checksum?) could be used when setting the cache file path to get around this problem?

**Comment by ambroisemaupate** [comment]
It’s a good idea to rely on the file checksum. I will implement it and make it optional if this _checksum comparison_ operation slow down too much image requests.

**Comment by ambroisemaupate** [comment]
@Toutouwai I’ve just released a new version with your suggestions. Check the Readme for options (checksum) and you can download the ZIP ready-to-use here: https://github.com/ambroisemaupate/intervention-request/releases/tag/v0.1.5
