### ISSUE TITLE
Option for default image

### ISSUE THREAD

**Issue by Toutouwai** [ambroisemaupate/intervention-request#8]
Intervention-request gives a fatal error if the source image is not found.
Rather than the throw the error it would be good to be able to specify a default image (or maybe just a block of solid colour) in the options to be displayed if the source image is not found.

**Comment by ambroisemaupate** [comment]
Thanks @Toutouwai for your suggestion. I can implement this but I think it’s not a _HTTP correct_ way of dealing it. When your image is absent, you should get an error response 404, if not, users and robots will believe that your replacement image is the true one, robots would even index it.

When you request an inexistant image directly using its link, Apache or Ngnix will output an error, I think we should have the same behaviour with Intervention-request.

If I implement your suggestion I will set it as an option to be enabled manually in the `Configuration` object.

**Comment by Toutouwai** [comment]
Hi, thanks for the reply.
I see your point and I agree that if the image isn't found there should be 404 Not Found response.
Does Intervention-request actually send a 404 Not Found response in this case though?
I get the response:

```
 Fatal error: Uncaught exception 'Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException' with message 'The file "../test.jpg" does not exist' in ...intervention-request\vendor\symfony\http-foundation\File\File.php:41 Stack trace: #0 ...intervention-request\src\InterventionRequest.php(99): Symfony\Component\HttpFoundation\File\File->__construct('../test.jpg') #1 D:\Websites\__www\cmsms-default\resize\index.php(65): AM\InterventionRequest\InterventionRequest->handle() #2 {main} thrown in ...intervention-request\vendor\symfony\http-foundation\File\File.php on line 41
```

But looking at the headers I don't see a 404 Not Found status.

**Comment by ambroisemaupate** [comment]
I’m working on it, it will be available in the next release.
