### ISSUE TITLE
Resized 8bit PNGs become 32bit PNGs

### ISSUE THREAD

**Issue by Toutouwai** [ambroisemaupate/intervention-request#9]
When resizing an 8bit PNG it becomes a 32bit PNG, making the file size unnecessarily large.

Ideally resized 8bit PNGs would stay as 8bit images while resized 32bit PNGs would stay as 32bit images. Is this possible?

**Comment by ambroisemaupate** [comment]
Hi @Toutouwai, I think it’s not possible, Intervention-request checks files against their mime-type and extension. So It can’t make the difference between PNG24 and PNG8.
